### ISSUE TITLE
error trying to connect: invalid dnsname - in Kubernetes

### ISSUE THREAD

**Issue by jlpettersson** [kube-rs/version-rs#3]
I cross-compiled this on MacOS to aarch64 and deployed to a local kind-cluster.
I built it with `rustls` for `kube-rs` with this line in `Cargo.toml`

    [dependencies]
    kube = { version = "0.57.0", default-features = false, features = ["client", "rustls-tls"] }

But I get many log-lines with this error:
```
ERROR HTTP{http.method=GET http.url=https://10.96.0.1:443/apis/apps/v1/namespaces/default/deployments? otel.name="list" otel.kind="client" otel.status_code="ERROR"}: kube::client: failed with error error trying to connect: invalid dnsname
```

This is when I run the `version`-app as a `Deployment` in Kubernetes.

Is this something expected? Is it a bug?

**Comment by kazk** [comment]
`rustls` is only supported in-cluster because of https://github.com/kube-rs/kube-rs/issues/153. In cluster support also requires kube 0.59.0 that was just released.

**Comment by jlpettersson** [comment]
@kazk Thanks!

When using 0.59.0 on the dependencies, I got this working.
